### ISSUE TITLE
subprocess.CalledProcessError: Command'

### ISSUE THREAD

**Issue by liutianyi00** [yuhongtian17/Spatial-Transform-Decoupling#12]
2024-06-15 18:07:08,163 - mmrotate - INFO - initialize RotatedRPNHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01}
2024-06-15 18:07:08,170 - mmrotate - INFO - initialize RotatedShared2FCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'layer': 'Linear', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
Traceback (most recent call last):
  File "./tools/train.py", line 198, in <module>
    main()
  File "./tools/train.py", line 193, in main
    meta=meta)
  File "/home/jbgs2024/mmrotate/mmrotate/apis/train.py", line 57, in train_detector
    cfg.device,
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device'
Traceback (most recent call last):
  File "./tools/train.py", line 198, in <module>
    main()
  File "./tools/train.py", line 193, in main
    meta=meta)
  File "/home/jbgs2024/mmrotate/mmrotate/apis/train.py", line 57, in train_detector
    cfg.device,
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device'
Traceback (most recent call last):
  File "./tools/train.py", line 198, in <module>
    main()
  File "./tools/train.py", line 193, in main
    meta=meta)
  File "/home/jbgs2024/mmrotate/mmrotate/apis/train.py", line 57, in train_detector
    cfg.device,
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device'
Traceback (most recent call last):
  File "./tools/train.py", line 198, in <module>
    main()
  File "./tools/train.py", line 193, in main
    meta=meta)
  File "/home/jbgs2024/mmrotate/mmrotate/apis/train.py", line 57, in train_detector
    cfg.device,
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device'
Traceback (most recent call last):
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/jbgs2024/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jbgs2024/miniconda3/envs/openmmlab/bin/python', '-u', './tools/train.py', '--local_rank=3', './configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py', '--seed', '0', '--launcher', 'pytorch']' returned non-zero exit status 1.

cuda version is 12.4

**Comment by yuhongtian17** [comment]
I guess that your mmcv or mmcv-full version may not be compatible with mmrotate version?
