### ISSUE TITLE
Report errors when i try to "CUDA_VISIBLE_DEVICES=0,1./tools/dist_train.sh ./configs/rotated_faster_rcnn/rotated_faster_rcnn_r50_fpn_1x_dota_le90.py 2

### ISSUE THREAD

**Issue by BiangBiangH** [yuhongtian17/Spatial-Transform-Decoupling#25]
I have read the relevant issues. I cannot directly run through this demo by following the steps in readme.The main issues were with the CUDA and pytorch environments. After continuous attempts, I resolved the environmental issues. When I tried to run it again, the following issues occurred. I suspect it may be a data issue, and I am not particularly clear which directory DOTA's test data should be placed in or how it should be stored. I tried to find the answer online, but it didn't solve the problem. Could you please give me some help.Here is my error message：

**2024-07-09 22:01:11,785 - mmrotate - INFO - Saving checkpoint at 1 epochs
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "./tools/train.py", line 198, in <module>
    main()
  File "./tools/train.py", line 187, in main
    train_detector(
  File "/data1/zhb/TZ/mmrotate/mmrotate/apis/train.py", line 144, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 126, in _do_evaluate
    results = multi_gpu_test(
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/mmdet/apis/test.py", line 107, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1115, in __init__
    self._reset(loader, first_iter=True)
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1148, in _reset
    self._try_put_index()
  File "/data1/Anaconda/envs/kky/lib/python3.8/site-packages/torch/utils/data/dataloader.py

**Comment by yuhongtian17** [comment]
The error info provided by you is not a complete one…? If possible, please upload screenshots instead of copying texts. Is there an error hint such as "Runtime Error: …"?

**Comment by BiangBiangH** [comment]
> The error info provided by you is not a complete one…? If possible, please upload screenshots instead of copying texts. Is there an error hint such as "Runtime Error: …"?
Sorry bro, now the following screenshots are the complete error:

<img width="716" alt="1720539519613" src="https://github.com/yuhongtian17/Spatial-Transform-Decoupling/assets/95524177/b8cbfbdd-2b4d-4b40-9510-feb9e6944163">

<img width="646" alt="1720539564099" src="https://github.com/yuhongtian17/Spatial-Transform-Decoupling/assets/95524177/2dbf2d90-ee06-4f5f-93bb-2e8049f791b8">

<img width="690" alt="1720539609764" src="https://github.com/yuhongtian17/Spatial-Transform-Decoupling/assets/95524177/65999fa0-98ac-4317-b394-f68ef7f815f9">

<img width="617" alt="1720539627901" src="https://github.com/yuhongtian17/Spatial-Transform-Decoupling/assets/95524177/4101df39-2acc-4266-a5fc-823ad890292e">

**Comment by yuhongtian17** [comment]
This error is due to the program not being able to find the dataset. Please confirm your dataset in [cfg](https://github.com/yuhongtian17/Spatial-Transform-Decoupling/blob/main/mmrotate-main/configs/_base_/datasets/dotav1.py#L3) exists.

**Comment by BiangBiangH** [comment]
> This error is due to the program not being able to find the dataset. Please confirm your dataset in [cfg](https://github.com/yuhongtian17/Spatial-Transform-Decoupling/blob/main/mmrotate-main/configs/_base_/datasets/dotav1.py#L3) exists.

Thank you for patiently answering. I have run the model successfully under your suggestion.
